

spring:
  application:
    # 服务名
    name: service-02
  cloud:
    nacos:
      discovery:
        # 服务注册中心
        server-addr: 119.3.62.74:8848
      config:
        server-addr: 127.0.0.1:8848
        prefix: ${spring.application.name}
        file-extension: yml
        group: DEV_GROUP



management:
  # 端点检查（健康检查）
  endpoints:
    web:
      exposure:
        include: "*"